### ISSUE TITLE
Physical: student feedback

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#42]
> I appreciated understanding some of the history and problems that you stated in the printing section. I felt like in a few sentences I understood why and how printing became so pervasive. I felt the other sections did not have as much to express why we are currently at this moment in time for the technology's maturity. I felt the "morphing" section is especially lacking since I am still a bit unsure what specifically characterizes morphing and how we arrived at wanting to utilize morphing as interaction pattern. Is Morphing a successor to physical buttons and switches that we physically change the state of.

> I sometimes get lost in many of these chapters of what I should take away from these technologies. The level of content seems to be written for designers to have a survey of technologies to perhaps use in their designs. But the way it is written it is not explicit for who this is written for. I wonder if this can be helped by creating a narrative of how these technologies can be included in the design process or what aspects technically designers should know while designing.

**Comment by andyjko** [comment]
I’ve been a bit confused with the bolded words in the past few
chapters. In the previous chapters, you bolded words that were key
vocabulary and often defined them. They’ve, for as far as I can
tell, all been novel terms in maybe the first 10 chapters. However,
in this chapter, you bolded “physical world” in the first paragraph
and neglected to define it. I guess no definition is technically
required, which may be why you didn’t define it. But it’s odd to me
that this word is treated differently. This happened in the 2D
chapter with “solidity, 
exaggeration,
and 
reinforcement,”
which I actually wanted defined. It seems like the purpose of the
bolded words has become more about emphasis and less about key new
vocabulary, but it seemed to have the latter purpose in the earlier
chapters.



Again, the quote used in the second paragraph of this chapter was
jarringly long. I see why you didn’t condense it, as it is an
interesting quote and impactful. But like my critique of one of the
previous chapters, it is presented before the point of this chapter
is presented, and is just this intimidating wall of text, so I
found myself glossing over it at least 5 times before really 
reading 
it.


I think “output” in this sentence in the third paragraph should be
“physical” output...or tangible output.



The past two chapters have already been about output, so this is
confusing. I actually went back to look how you called the past two
chapters because I could’ve sworn they were about output too, but
this sentence made it seem like this was an exciting new topic. I
think if you put in “physical” as the distinguishing factor from
the last two, then it is exciting and new.


“Charles
Babbage,
for example, the English mathematician and philosopher who first
imagined the concept of a programmable digital computer in 1822,
also imagined a mechanical printing device that could print the
results of his imagined differencing machine.” 
   

This is a long sentence with so many clauses that it ruins the flow
and gets confusing (funny that I point this out, because I know my
own sentences have been pretty un-pithy in this critique). It might
be improved just by switching Charles Babbage and For example. That
way, the descriptor, “the English mathematician,” is not so
separated from who it is describing.   


“The 
diversity 
of computer printing technology we have today, including machines
that use toner, liquid ink, solid ink, or dye-sublimation, 
come 
directly from these imagined futures of physical computer
output.” 
   

I think since “diversity” is the subject, and it is a singular
subject, and “including machines [...]” is just an interrupter
phrase between two commas, the verb “come” should actually be
comes.




I feel like there’s some kind of transition missing here, both
between the first two sentences and the stuff about Labo, and
between this whole section and the rest of the chapter. You go from
“Screens are rigid and constrain things” to “For example, Nintendo
Labo wraps cardboard around rigid screens to create cool new
experiences.” I feel like this is saying screens are bad for being
rigid and this constrains creativity. But Nintendo’s Labo is so
cool and creative that it doesn’t quite fit the bill for being an
example. Labo doesn’t feel constrained to me by the way you phrased
it and praise it. I guess I’m not quite sure what you’re trying to
say in these sentences.


On why it seems like it’s missing a transition from the rest of the
chapter, I’m unsure why you just suddenly jump to 
screens 
specifically. We were just talking about 3D printing. I think it’s
because you’re talking about output and GUIs have screens I guess
to usually output things, but I thought we were talking about
physical output in this chapter...we covered visual output in the
previous chapters. Maybe a call back to why we’re suddenly talking
about screens now would be beneficial. This kind of is exacerbated
by how you start off the haptics paragraph. Because there you’re
again, starting off talking about how the physical form of the
interfaces...which sure, it’s physical. But I thought this chapter
was physical 
output. 
It’s not the case where the Labo changes cardboard structure
automatically based on the buttons you press.


That being said, the haptics section as a whole is fine. It reeled
it back into being about output. But I think this form of interface
section is just out of place and making these weird transitions and
confusion. I actually did keep scrolling up to the top of the
chapter to see if I wasn’t just imagining this chapter was supposed
to be about output still and not just everything
physical.

**Comment by andyjko** [comment]
> The chapter was great, but the number of YouTube examples really broke up my reading. I would like it if the videos were laid off to the side since I like finish my reading before watching the videos since I tend to lose focus when switching between text and video.

> I also liked the broad overview of each type of physical output, but would have liked a more in depth overview of morphing. I found the examples great, but maybe some more analysis as to why some of the ideas haven't really seen wide use would be great.

**Comment by andyjko** [comment]
> 1) There were a lot of videos in this chapter, personally I found them to be a bit distracting from the reading experience. Perhaps consider limiting number of videos?
> 2) The morphing section seemed a bit brief/abrupt? I didn't feel like I had a great understanding after reading this section.

**Comment by andyjko** [comment]
> This chapter details a wide spectrum of current research in physicalizing digital output. As was the case with other recent chapters, including 3D interactions and body-based input, the surveyed variety overwhelms theoretical models. This is not a critique of the writing, but of the subject matter. Researchers wrestle to "solve" the embodied world in numerous ways because its challenges are is so complex.

> I believe this chapter could provide a stronger overarching model by spending more time discussing the basic mechanics of traditional paper printers, and use these elements as a model for other techniques. Paper printers require transmission of digital data to an X,Y grid, the storage and interfacing of malleable materials (paper and ink), the ability to continuously feed these materials into each other through precise mechanical motion, and periods of material "warm up" and "cooling" time, which is trivial for printer papers but can critical for more solid printing materials. These elements track to other technologies discussed in this chapter - even morphing and haptics technologies, to some degree.

> It could also be helpful to revisit the concept of interface as mediator, and map this model to the mediation of physical / digital materials, ex. light to matter and matter to light. As mediator, the interface is responsible for defining its areas of information transmission and information compromise. Considering printing, haptics, and morphing from this perspective helped me wrap my head around the underlying dynamics of each individual technology.

**Comment by andyjko** [comment]
Many students enjoyed the discussion on the ethics of some of these physical computing ideas (e.g., shocking people, unintended side effects of small robots). Perhaps discuss.

**Comment by andyjko** [comment]
> 1. The video link to "Dot matrix printers can also be used to play inspiring montage music" is a little bit confusing. I do understand the video content, but I don't see how it relates back to the chapter content and where it was placed in this chapter. Before and after the video link, the chapter was talking about printing, or more precisely, practical printing where the printed result has a physical form - either text or 3D objects. However, the dot matrix printer making music seems less relevant to these contents. 

> 2. One in-text link is not wokring: "For example, one work displayed a high resolution visual form with tactile feedback from a low-resolution grid of actuated pins that move up and down, giving a sense of high-resolution tactile feedback (Abtahi et al 2018)."

**Comment by andyjko** [comment]
Elaborate on what authorship challenges exist. Knowing what's printable, what's not. Also the IP issues.

**Comment by andyjko** [comment]
> 1. The paper gives lots of interesting real world examples for each category. But as some examples only give few details, sometimes it is hard for me to understand the whole working mechanism. Is there a clearer way to illustrate these examples?
> 2. Some knowledge and examples given in the article are quite new and innovative for me. I wonder if it is possible to include some information that guides us to relate these new knowledge to current design.

**Comment by andyjko** [comment]
> In the beginning of this reading, you share a quote from the seminal paper "Tangible Bits: Towards Seamless Interfaces between People, Bits and Atoms." Hiroshi Ishii and Brygg Ullmer argument in that quote is very complex. I had to read it over and over to understand it better. I think more clarification and an easy breakdown of what they are saying is necessary.
> When you discuss 3D printing and how much it's changed and become accessible over time, it might be good to mention how the price of it has changed, allowing more and more people to design 3D objects.
> I know there are some chef's that use 3D printing to make really amazing pastries and foods. You can check out one example here: http://www.businessinsider.com/ukrainian-pastry-chef-makes-geometric-desserts-using-a-3d-printer-2017-10. I think it would be a great thing to mention this in the chapter to show how creatively all types of people are able to use 3D printing.
> I didn't understand what "ticker tape" was in the reading. I had to google it. Maybe a one sentence explanation saying something along the lines of it is "a paper strip on which messages are recorded" would be helpful. For some reason when I saw the image of the women holding it, it really looked like a strip from a roll of movie tickets to me. 
> The simulating impact video was very cool.

**Comment by andyjko** [comment]
> I have met Hiroshi Ishii last year and I got inspired by his theory about Tangible Bits and the future of tangible interaction. I think maybe in the future iteration, you can include the diagram he made for this theory. (Please see the attached photo)
> I think the ways of physical output are various and interesting as you discussed in the chapter. Is there a way in the future iteration, you can mention some non-ordinary paradigms that using physical object as input and digital content as output? Such as I/o Brush http://tangible.media.mit.edu/project/io-brush/

**Comment by andyjko** [comment]
> After reading the chapter Physical output, I love how you put so many videos to demonstrate each unique techniques and am surprised to see the Switch Labo (how quick the update of the book is). 
> Although the new technologies of how people generate physical out are amazing, it might be also meaningful to talk about some mature technology that people use very often in reality. For example, even though laser cut is a tool for 2d shapes, 2d shapes can still be formed to create 3d objects. Also, besides 3d print, 3-axis CNC machines can also be used as a tool to generate 3d object with more accuracy.

**Comment by andyjko** [comment]
> I appreciate that you provide severals distinguishable paradigms about physical output. I think it will be more beneficial for audience at learning aspect if you can talk about some areas or paradigms that integrate multiple physical inputs together, which could inspire audiences by more interdisciplinary applications.

> I am interested in biological design. When talking about interactive objects, I think BioLogic (https://tangible.media.mit.edu/project/biologic/) is a very good example to demonstrate a new type of programmable materials using biological techniques. Also, the tangible interfaces at the MIT Media Lab have done a lot of projects about programmable shape-changing materials. In the future reading session, maybe we could share information about specific research labs doing related topics. If students want to dig deeper in this field, they can search and learn more from these labs.

**Comment by andyjko** [comment]
> 1) I felt the Morphing section should have had a more defining introduction paragraph before going into the examples.

> 2) The Eye of the Tiger video was really cool, but it wasn't mentioned in the printing section. I would have liked a transition to it and reasoning for how printing can create other outputs like music.
