### ISSUE TITLE
Theory: student critiques

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#71]
1. It might be nice if the chapter touches a little on how sometimes these interface theories may not be necessarily followed in practice when designers are placed in an environment with stakeholders that may have competing priorities. For example, hidden close buttons on modals are really prevalent in ads and cases like this illustrate how business/marketing stakeholders may still win the battle sacrificing usability in hopes of increasing sales.

 2. Another case I thought about when reading through this chapter was the case of Snapchat. The app is intentionally designed against all existing conventions but was still successful. Why was this so, and when is the proper time for designers to go against conventions?

3. A gesture that bothers me in some social media apps now is the ability to swipe left on the home screen of an app which goes to a camera (Instagram). This affordance lacks a signifier for a first time user but has become so popular. Why has a gesture like this become a convention even if it flies against the theories of this chapter?

**Comment by andyjko** [comment]
An affordance is a property of what can be done to an interface in order to produce some effect.

 

- - - - -

 

I think what is unclear from this statement is that affordance is not a property of the interface itself but actually the relationship between the interface and a potential user.

 

“The term affordance refers to the relationship between a physical object and a person (or for that matter, any interacting agent, whether animal or human or even machines and robots). An affordance is a relationship between the properties of an object and the capabilities of the agent that determine just how the object could possibly be used”.

 “We are used to thinking that properties are associated with objects. But affordance is not a property. An affordance is a relationship. Whether an affordance exists depends upon properties of both the object and the agent.”

 (Norman 2013)

Therefore, affordances define how an object can be interacted with but are specific to the person acting upon them or perceiving them (Gaver 1991).

**Comment by andyjko** [comment]
When Don Norman talks about the two gulfs, he says that the difficulties reside in the design of devices and not in the people attempting to use them (Norman 2013). Based on my understanding of his book, an interface can help bridge the gulf of execution by successfully communicating to the user, what outcomes are possible and how to achieve them. In contrast, I feel that the required reading takes the responsibility away from the interface and puts the onus on the user. It highlights the role of the user when it comes to learning affordances but de-emphasizes the deliberate use of signifiers in good interface design.

 

While probably intentional, I personally find this confusing because the intention behind the theory shared was to keep user interfaces at the center and humans at the periphery, whereas some of the major takeaways are more from the user’s perspective.

**Comment by andyjko** [comment]
1. Concise definitions of theories.

For example, the definition of the Gulf of Execution is: “This gulf describes the knowledge gap that a person has when trying to learn what actions they can perform on an interface that will allow them to achieve their goal.” This sentence could be simplified into: “Gulfs of execution are gaps between the user’s goal and the input they have to provide to achieve it.”

2. Typo

In the paragraph that talks about conventions, there is a small typo with the word “minimizing”.

“Alternatively, interfaces might even try to anticipate what people want to do, personalizing what's available, and in doing so, miniizing how much a person has to learn.”

3. More visual aids

Abstract theories like the affordance and the signifier could be explained clearer with simple diagrams instead of just text.
