### ISSUE TITLE
Declarative: student feedback

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#73]
Chapter Critique

1. This is somewhat of a critique overall, but the readability of this chapter was particularly challenging for me on an accessibility level. This chapter had larger chunks of text than the previous chapters. While for you average individual this usually isn't a problem, it makes reading the content for someone who is dyslexic challenging. If there is a way to add in even more visuals or design out the content in some way that would definitely help, but also understand that the majority of your readers don't have learning disabilities. 

2. I would have liked to see more detail on the six barriers. That point seemed a bit glossed over

3. It would be helpful to have brief definitions of previous concepts as you move through each chapter. I had to go back to previous chapters and my notes to double check definitions or concepts.

**Comment by andyjko** [comment]
Overall I really like the chapter! The metaphors are easy to understand, and it is one of those rare explanations that is equally helpful for people with and without declarative interface experience. With that being said, here's what I would change:

#1

Instead of introducing Blackwell's three critical attributes of programming like this: "The distinction between programming interfaces and interactive interfaces comes down to three critical attributes of programming (Blackwell 2002 (Links to an external site.)Links to an external site.)" and following that with a bulleted list, try branding it a bit to make it stick in people's minds, refer to it by that brand name (I suggest something like "Blackwell's Critical 3"), and follow it with a numbered list.

 

#2

On your next bulleted list in the chapter, maybe try giving each one an icon? I don't know if this is true for most people, but things like that really help me retain information.

 

#3

After my initial read through, I went back to study a bit for the quiz and had a hard time finding the section I was looking for. Maybe you could break the chapter up into sections with headings? My suggested sections would be:

1. What are declarative interfaces?

2. Gulfs of execution and evaluation

3. HCI researcher contributions

(the images in the latter half of the chapter do a great job of breaking up the remaining sections)

 

(sorry that all my suggestions are reading comprehension tricks, that's just what I have trouble with)

**Comment by andyjko** [comment]
Critique of the chapter:

 

1. I find the way that the description of abstractions ends with the inclusion of a GUI manipulation a bit confusing. I think this point could be brought in at the end when the reader has a better understanding of declarative interfaces and the ways in which graphical interfaces are different (but still have similar properties!). 

 

2. The six categories you have created could be more illustrative if they were framed around what problems exist for execution and what problems exist for evaluation?

 

3. Similarly, I found myself re-writing your categorical gulfs into questions, this was a useful way for me to conceptualize them:

Execution Barriers:
Design: What can be expressed?
Selection: How best can we express it?
Use: How can we use functions in an API? What inputs do they need?
Coordination: How can all the parts work together?
Evaluation Barriers:
Understanding: What went wrong? What could have gone wrong?
Information: How did the program execute?

**Comment by andyjko** [comment]
#1

“An inherent side effect of using notations is that one must also use abstractions to refer to a computer's actions.”

As someone from an art & design background, the distinction between notation and abstraction is still unclear to me. Are we abstracting the notation? If a notation is a system of symbols and characters that represent an idea then wouldn’t abstractions be predetermined by the notation? In which case, why are they called abstractions? Whether abstractions are inherent to the program or at the programmer’s discretion, could be made clearer.

 

#2

“Commands, names, and relative path references are all abstractions in that they remove detail, allowing a user to interact with the ideas of files and file movement. Visual icons that represent files are also abstractions, but they support direct manipulation, such as moving files from one folder to another.”

When I read this my first question was what is the need for abstraction? My assumption was that by making the code more abstract and by hiding its complexity wouldn’t it be harder to understand? I went through this example (Links to an external site.) of a coffee machine to try and understand how abstractions make code simple and easy to use. I think linking the need for abstractions to increasing efficiency could be called out more explicitly.

 

#3

“Because textual programs are parsed according to a formal grammar, there are numerous ways to violate the grammar, requiring a user to know the rules of the grammar to write correct programs.”

I found this slightly confusing. By ‘formal grammar’ do you mean the same thing as notation? If yes then linking it back to that might be more helpful since we read about it earlier in the chapter. Not only would that solidify the reader’s understanding of the term, but it would also reduce the chances of being thrown off by new terminology.

**Comment by andyjko** [comment]
#1

“An inherent side effect of using notations is that one must also use abstractions to refer to a computer's actions.”

As someone from an art & design background, the distinction between notation and abstraction is still unclear to me. Are we abstracting the notation? If a notation is a system of symbols and characters that represent an idea then wouldn’t abstractions be predetermined by the notation? In which case, why are they called abstractions? Whether abstractions are inherent to the program or at the programmer’s discretion, could be made clearer.

 

#2

“Commands, names, and relative path references are all abstractions in that they remove detail, allowing a user to interact with the ideas of files and file movement. Visual icons that represent files are also abstractions, but they support direct manipulation, such as moving files from one folder to another.”

When I read this my first question was what is the need for abstraction? My assumption was that by making the code more abstract and by hiding its complexity wouldn’t it be harder to understand? I went through this example (Links to an external site.) of a coffee machine to try and understand how abstractions make code simple and easy to use. I think linking the need for abstractions to increasing efficiency could be called out more explicitly.

 

#3

“Because textual programs are parsed according to a formal grammar, there are numerous ways to violate the grammar, requiring a user to know the rules of the grammar to write correct programs.”

I found this slightly confusing. By ‘formal grammar’ do you mean the same thing as notation? If yes then linking it back to that might be more helpful since we read about it earlier in the chapter. Not only would that solidify the reader’s understanding of the term, but it would also reduce the chances of being thrown off by new terminology.
