### ISSUE TITLE
Interactive: student feedback

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#74]
I think direct manipulation has played an important role in shaping our interactive interfaces throughout these years and it continues to exert a strong influence on the design of interactive software today. Explaining direct manipulation after introducing WIMP provides us with a limited definition of this term, however it is important to understand that it does not necessarily imply the use of windows or graphical output. For example, using a combination of tactile and sonic devices and software, direct manipulation concepts can be applied to interfaces for vision-impaired users.

Another suggestion is to add a brief section about GUI and then discuss WIMP after that section since WIMP systems derive from such systems. Then the difference between GUI and WIMP can be explained in a concise manner. Knowing that all WIMP systems use graphics as a key element, therefore are GUIs, however the reverse is not true, provides us with a more accurate understanding of the definitions of these concepts and the way they have been used.

One other recommendation is to discuss post-WIMP in this chapter. Understanding the limitations of WIMP and also knowing why WIMP interfaces are not optimal for working with complex tasks can help us better understand the background of interactive interfaces.

**Comment by andyjko** [comment]
Chapter Critique:

In class you mentioned you will discuss pointers in later chapters, but I think even a short paragraph here would keep it from feeling like you missed it.
I think with Icons there’s a clear point to be made that the “visual access” also includes quick legibility that includes a lot more information than a file name. The icon indicates what kind of file and even sometimes what kind of content it contains (i.e. Mac OS shows what is inside the file in the icon preview).
With dialogues and forms there’s a good point to be made here about requiring less knowledge of the user. Because the system asks for the information needed to complete a command it reduces the use barrier of declarative interfaces.

**Comment by andyjko** [comment]
Interactive Interfaces
 

i) I think this chapter, in particular, required a lot more photos than it had. There were a number of examples given, like the scroll bar “knob”, and other ideas proposed in paragraph 1 under Windows, icons, menus, and pointers. Also, there might be a technical issue since I wasn’t able to click on any of the links that you provided along with the examples. Either way, just a few images of the examples that peak interest should be provided for better context.

 

ii I think the overall tone of the chapter was more of a conversation. I felt that the chapter could’ve been segmented in the form of

 

window managers
icons
menus
dialogs and forms
widgets
copy and paste
 

or by the issues being resolved. like,

 

Providing a visual structure to large amounts of content (windows and window managers)
Accessing programs without a command line (icons and menus), etc…
 

iii I think the last paragraph ties back to the explanation you gave in class after the first reading which was a nice recap. It’s not a critique, just a small observation.
