### ISSUE TITLE
2D: Student feedback

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#96]
* Showing a static picture of CRT is hard to understand how it actually works. Would be helpful to include a link of a video (could be an animation) that labels the different parts of elements (ex: three electron guns and phosphorescent) and demonstrates what’s described in the paragraph in action. Just from reading the technical description was hard to understand for someone like me who has no engineering background at all.
* Would be nice to explain more in details the techniques from computer graphics that ensure a high level of graphical fidelity. For example, I have no idea what anti-aliasing is and the image that is included in the reading does not explain well what it is. It was later mentioned briefly in the typographic section which could have been nice to explain earlier when it’s first introduced in the reading.
* After reading the entire chapter, I wasn’t very sure why the first image of this chapter is an image of Pong. I think it would be nice to explain more clearly the connection of why it’s chosen as the first image of this chapter and the significance of Pong to 2D rendering. I thought this chapter would talk about how 2D output and its implementation in gaming based on the first image.

**Comment by andyjko** [comment]
1. In the Graphics section, you write "In a way, all computer graphics are simulations, reconstructing complex visual scenes out of more primitive shapes, from powerful windowed operating systems to photorealistic scenes computer generated animated movies." This is a minor critique on grammar, but I believe you meant to write "photorealistic scenes in computer-generated animated movies". I think you could say the same thing with fewer words, maybe like "photorealistic computer-generated movies."

2. Maybe it's just that I'm a typography nerd, but I would love to see more discussion of advancements in typography on computing devices. Your most recent example is from 2006, but typography has expanded so much since then–variable fonts come to mind. Google Fonts started in 2010 and has heavily influenced the look of much of the web.

3. The section on data felt out of place in the context of 2D visual outputs. The other sub-sections deal with the basic building blocks of 2D displays, whereas the data section focused specifically on data visualizations (which encompass graphics, typography, and animation). Maybe it could be placed last, drawing a greater connection to the sections which came before it as an example that bridges all of the preceding sections together.

**Comment by andyjko** [comment]
The chapter mentions countless ways of storing and compressing pixel data (bmp, pict, gif, tiff, jpeg, png). I believe the differences between these formats is highly misunderstood. Would be beneficial to explain their variations.
The chapter sometimes confuses between a font vs typeface. The typeface is the visual design, while the font is the software that allows one to install, access, and output the design. Instead of "The original Mac fonts" it should probably be called "The original Mac typefaces"
The chapter should also mention Google Material Design along with Apple's Core Animation. They work on the same framework but have different underlying philosophies.

**Comment by andyjko** [comment]
I managed to find the credit for the image for the original Mac fonts. It was designed in 1983 by Susan Kare. Source: http://kare.com/apple-icons/ (Links to an external site.)Links to an external site.

One thing I appreciate about the UIST textbook is that it gives overviews on the history, present, and often times a sneak peek into the future. I enjoyed reading up on the history of 2D displays for CRTs to LCDs to LEDs. Experts predict that laser diode displays will come after LEDs for being even more compact and energy efficient. I think it would be worthwhile to include a short section on laser diodes to give a taste for where the future of displays will be headed. 

In the third paragraph under typography, I wonder if the second sentence would flow better if it read, "...and that it was central for differentiating the Mac..." instead of "...and that it was central to differentiating the Mac..".
