### ISSUE TITLE
Help: student feedback

### ISSUE THREAD

**Issue by amyjko** [amyjko/user-interface-software-and-technology#99]
It would be helpful to explain the theories of help through a user scenario besides explaining in a broad context of the theory. This way the reader can relate to it more since all of us in some ways has dealt with help in our everyday life.
I thought this video of Clippy is quite interesting and helpful than reading a Wiki page. Could consider linking it to the chapter besides the Wikipedia page. Would also be interested to learn why clippy failed.
Whatever Happened to Clippy? (Links to an external site.)Links to an external site.
Whatever Happened to Clippy?
Could be interesting to include examples of help interface beside on those on the computers. For instance, I always have issues with the help interface on printers whenever papers get jammed.

**Comment by andyjko** [comment]
1. I think there should be a separate section about Instruction. It seems to be a major problem that no one has figured out a solid solution yet, and it seems to be of significance to the concept of helping the users.

2. One question that I have after reading the chapter is whether the complexity of the app scales together with the amount of help the users need? Do users have more problems using modern apps because they are naturally complicated and it's impossible for anyone to use it.

3. Is there any way to "confirm help"? Maybe you can add another section about this.

**Comment by andyjko** [comment]
1. I think there should be a separate section about Instruction. It seems to be a major problem that no one has figured out a solid solution yet, and it seems to be of significance to the concept of helping the users.

2. One question that I have after reading the chapter is whether the complexity of the app scales together with the amount of help the users need? Do users have more problems using modern apps because they are naturally complicated and it's impossible for anyone to use it.

3. Is there any way to "confirm help"? Maybe you can add another section about this.

**Comment by andyjko** [comment]
Talk about onboarding experiences and how they can reduce the gap of execution for users in modern apps.
Could present a few different type of onboarding experiences that are popular in modern apps. This can be presented in a way to prompt the reader to think deeply about the differences between onboarding experiences and what works/doesn't work. 
Would also be interesting to hear about the disappearance of manuals especially in games. Most games nowadays no longer come with the manual and players are usually forced to learn by playing. This may actually help players be immersed quicker into the game. A lot of the material in the physical manuals have also moved into the game itself in the form of better tutorials or digital manuals.The lack of manuals has also extended to the tech sector such as lack of manuals in Apple products.

**Comment by andyjko** [comment]
1.There’s a typo in the second last sentence of the section “Search for Help”. Instead of “the speak it”, it should be “they speak it”.



2.In app design, especially in mobile apps, there are tips, animations and tutorials to educate new users. Probably can talk about the difference between mobile app help and desktop app/web help.



3.Would love to know more about how AI and ML are used in help.

**Comment by andyjko** [comment]
-A quick recap of Normans "Breakdowns" would be useful.

-"if the user takes no action on a page for 1 minute, offer to chat" I wonder how effective this is? In an unobtrusive place, this would be fine but I could see it being distracting or annoying. What are some drawbacks of this form of help?

-I read the Akers article and I found this type of research to be really interesting. Maybe expanding on this as an inexpensive method of gaining insights and providing other similar examples?
